import React, { useState } from "react";

const faqData = [
  {
    question: "How does the AI outline and drafting process work?",
    answer: "Our system runs an automated content generation pipeline. When you input a topic, niche, or prompt, our AI Structuring Engine generates a target audience profile, marketing angles, and a comprehensive table of contents. Once approved, the Drafting Engine writes each chapter sequentially, utilizing running memory anchors to maintain narrative continuity and prevent text repetition."
  },
  {
    question: "What file formats are supported for exporting eBooks?",
    answer: "You can download your eBook in multiple publication-ready formats. Currently, we support high-fidelity PDF documents, editable MS Word (DOCX) files, standardized EPUB packages for e-readers, and clean Markdown (MD) files for easy editing and importing into other platforms."
  },
  {
    question: "Do I own the full rights to the books generated by eBookAI?",
    answer: "Yes, absolutely! You own 100% of the copyrights and commercial publishing rights for any eBook created using our platform. You can distribute them, sell them on platforms like Amazon Kindle KDP, or use them as lead magnets for your marketing campaigns."
  },
  {
    question: "Can I customize the cover design and styling?",
    answer: "Yes, our Editor workspace features a custom paperback Cover Builder. You can define cover gradient schemes (Midnight Blue, Cosmic Purple, Emerald, Sunset, Charcoal) and layout formats (Modern, Editorial, Minimalist, Geometric). Furthermore, we are rolling out an advanced Export Styling Builder to configure custom page margins, font pairings, page headers, footers, and alignments."
  },
  {
    question: "How does the Discover Library and reader reviews work?",
    answer: "The Discover Library is our social hub where you can publish your finished eBooks. Readers can browse books by genre or search keywords. Each book records its reading statistics (total reads, average ratings) dynamically from reviews submitted by readers in the system. Your author profile dynamically aggregates these metrics in real-time."
  }
];

const FAQ = () => {
  const [activeIndex, setActiveIndex] = useState(null);

  const toggleFAQ = (index) => {
    setActiveIndex(activeIndex === index ? null : index);
  };

  return (
    <section id="faq" className="py-24 bg-bg-secondary border-t border-b border-border-primary scroll-mt-20 transition-colors duration-250">
      <div className="max-w-4xl mx-auto px-6">
        
        {/* Section Header */}
        <div className="text-center mb-16">
          <span className="text-[10px] font-extrabold uppercase tracking-widest text-emerald-700 bg-emerald-50 px-3 py-1 rounded-full dark:bg-emerald-950/30 dark:text-emerald-450">
            FAQS & HELP
          </span>
          <h2 className="font-display font-light text-3xl sm:text-4xl text-text-primary tracking-tight mt-4 mb-3">
            Frequently Asked Questions
          </h2>
          <p className="text-text-secondary text-xs sm:text-sm max-w-lg mx-auto leading-relaxed">
            Everything you need to know about the AI eBook Creator platform, publishing rights, and exporting.
          </p>
        </div>

        {/* FAQ Accordion List */}
        <div className="flex flex-col gap-4">
          {faqData.map((item, index) => {
            const isOpen = activeIndex === index;
            return (
              <div 
                key={index}
                className={`bg-bg-primary border rounded-[20px] transition-all duration-300 ${
                  isOpen 
                    ? "border-emerald-700/30 shadow-lg shadow-emerald-700/[0.02]" 
                    : "border-border-primary hover:border-text-muted shadow-sm"
                }`}
              >
                {/* Accordion Trigger */}
                <button
                  type="button"
                  onClick={() => toggleFAQ(index)}
                  className="w-full flex items-center justify-between px-6 py-5 text-left cursor-pointer focus:outline-none"
                >
                  <span className="text-xs sm:text-sm font-bold text-text-primary transition-colors duration-200">
                    {item.question}
                  </span>
                  
                  {/* Rotating Chevron/Plus Icon */}
                  <div className={`h-7 w-7 rounded-full flex items-center justify-center transition-all duration-300 ${
                    isOpen ? "bg-emerald-50 dark:bg-emerald-950/30 text-emerald-700 dark:text-emerald-450" : "bg-bg-secondary text-text-muted"
                  }`}>
                    <svg 
                      className={`w-4 h-4 transform transition-transform duration-300 ${isOpen ? "rotate-180" : ""}`} 
                      fill="none" 
                      stroke="currentColor" 
                      viewBox="0 0 24 24"
                    >
                      <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2.5" d="M19 9l-7 7-7-7" />
                    </svg>
                  </div>
                </button>

                {/* Accordion Content with smooth height logic */}
                <div 
                  className={`overflow-hidden transition-all duration-300 ease-in-out ${
                    isOpen ? "max-h-[300px] border-t border-border-primary" : "max-h-0"
                  }`}
                >
                  <p className="px-6 py-5 text-xs sm:text-sm text-text-secondary leading-relaxed">
                    {item.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>

      </div>
    </section>
  );
};

export default FAQ;
